# Generated by Django 4.0.5 on 2023-05-28 19:19

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0004_remove_users_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='country',
            field=django_countries.fields.CountryField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='pyment_type',
            field=models.CharField(choices=[('paypal', 'paypal'), ('credit card', 'credit card'), ('cash', 'cash')], default=123, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='sales',
            field=models.PositiveIntegerField(default='1'),
            preserve_default=False,
        ),
    ]
