# Generated by Django 4.0.5 on 2023-05-28 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0005_client_country_client_pyment_type_client_sales'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='pyment_type',
            new_name='payment_type',
        ),
    ]
